i18n.map('en',{
	ADMIN_USERS_EDIT:'Edit Profile',
	ADMIN_USERS_CHANGE_PASSWORD:'Change Password',
	ADMIN_USERS_EDIT_USERNAME:'Username',
	ADMIN_USERS_EDIT_EMAIL:'Email',
	ADMIN_USERS_EDIT_NEW_PASSWORD:'New Password',
	ADMIN_USERS_EDIT_CONFIRMPASSWORD:'Confirm Password',
	ADMIN_USERS_EDIT_OLD_PASSWORD:'Old Password',
	ADMIN_USERS_PROFILE:'My Profile',
	ADMIN_USERS_PROFILE_PICTURE:'Profile Picture',
	ADMIN_USERS_EDIT_SAVE:'Save',
	ADMIN_USERS_EDIT_CANCEL:'Cancel',
	ADMIN_USERS_PROFILE_EDIT:'Edit'
})