i18n.map('en',{
	ADMIN_MENU_MENUITEMS:'Menu Items',
  	ADMIN_MENU_MENUITEMS_ADDMENUITEM: 'Add Menu Item',
  	ADMIN_MENU_MENUITEMS_EDITMENUITEM:'Edit HTML Blocks',
  	ADMIN_MENU_MENUITEMS_ADDMENUITEM_FORM_TITLE:'Title',
  	ADMIN_MENU_MENUITEMS_ADDMENUITEM_FORM_DESCRIPTION:'Description',
  	ADMIN_MENU_MENUITEMS_ADDMENUITEM_FORM_MENUITEMTYPE:'Menu Item type',
  	ADMIN_MENU_MENUITEMS_ADDMENUITEM_FORM_PARENT:'Parent',
  	ADMIN_MENU_MENUITEMS_ADDMENUITEM_FORM_SAVE:'Save',
  	ADMIN_MENU_MENUITEMS_ADDMENUITEM_FORM_CANCEL:'Cancel',
    ADMIN_MENU_MENU:'Menu',
    ADMIN_MENU_MENUITEMS_ADDMENUITEM_DEFAULT:'Default',
  	
})