i18n.map('en',{

  ADMIN_COTNENTS_CATEGORY_CATEGORY:'Categories',
  ADMIN_COTNENTS_CATEGORY_ADDCATEGORY: 'Add Category',
  ADMIN_COTNENTS_CATEGORY_EDITCATEGORY:'Edit Category',
  ADMIN_COTNENTS_CATEGORY_ADDCATEGORY_FORM_CATEGORYNAME:'Category name',
  ADMIN_COTNENTS_CATEGORY_ADDCATEGORY_FORM_SAVE:'Save',
  ADMIN_COTNENTS_CATEGORY_ADDCATEGORY_FORM_CANCEL:'Cancel',
  ADMIN_COTNENTS_CATEGORY_ADDCATEGORY_FORM_ARTICLE_NUMBER:'No. of Article in row'
});