i18n.map('en', {
  ADMIN_COTNENTS_ARTICLES_ADDARTICLES: 'Add Article',
  ADMIN_COTNENTS_ARTICLES_EDITARTICLE:'Edit Article',
  ADMIN_COTNENTS_ARTICLES_ADDARTICLE_FORM_TITLE:'Title',
  ADMIN_COTNENTS_ARTICLES_ADDARTICLE_FORM_CATEGORY :'Category',

  ADMIN_COTNENTS_ARTICLES_ADDARTICLE_FORM_TAGS:'Tags',
  ADMIN_COTNENTS_ARTICLES_ADDARTICLE_FORM_ARTICLE:'Article',
  ADMIN_COTNENTS_ARTICLES_ADDARTICLE_FORM_METAKEYWORD:'Meta Keyword',
  ADMIN_COTNENTS_ARTICLES_ADDARTICLE_FORM_METADESCRIPTION:'Meta Description',
  ADMIN_COTNENTS_ARTICLES_ADDARTICLE_FORM_SAVE:'Save',
  ADMIN_COTNENTS_ARTICLES_ADDARTICLE_FORM_CANCEL:'Cancel',
  ADMIN_COTNENTS_ARTICLES_ADDARTICLE_FORM_ACTIONS:'Actions'
});	

i18n.map('fr', {
  ADMIN_COTNENTS_ARTICLES_ADDARTICLES: 'Afhgdfhdd Article',
  ADMIN_COTNENTS_ARTICLES_EDITARTICLE:'Edit fghfghArticle',
  ADMIN_COTNENTS_ARTICLES_ADDARTICLE_FORM_TITLE:'Titgfhfghfle',
  ADMIN_COTNENTS_ARTICLES_ADDARTICLE_FORM_CATEGORY :'Cafghfghfgtegory',

  ADMIN_COTNENTS_ARTICLES_ADDARTICLE_FORM_TAGS:'Tagfghfghs',
  ADMIN_COTNENTS_ARTICLES_ADDARTICLE_FORM_ARTICLE:'Articlfghfghe',
  ADMIN_COTNENTS_ARTICLES_ADDARTICLE_FORM_METAKEYWORD:'Metafghfgh Keyword',
  ADMIN_COTNENTS_ARTICLES_ADDARTICLE_FORM_METADESCRIPTION:'Metafghfgh Description',
  ADMIN_COTNENTS_ARTICLES_ADDARTICLE_FORM_SAVE:'Savfghfge',
  ADMIN_COTNENTS_ARTICLES_ADDARTICLE_FORM_CANCEL:'Cancfghfgel',
  ADMIN_COTNENTS_ARTICLES_ADDARTICLE_FORM_ACTIONS:'Actfgfgions'
});			
