i18n.map('en',{
	ADMIN_MENU:'Menu',
  	ADMIN_MENU_ADDMENU: 'Add Menu',
  	ADMIN_MENU_EDITMENU:'Edit Menu',
  	ADMIN_MENU_ADDMENU_FORM_TITLE:'Title',
  	ADMIN_MENU_ADDMENU_FORM_DESCRIPTION:'Description',
  	ADMIN_MENU_ADDMENU_FORM_DELETE:'Delete',
  	ADMIN_MENU_ADDMENU_FORM_EDIT:'Edit',
    ADMIN_MENU_ADDMENU_FORM_ACTION:'Action',
  	ADMIN_MENU_ADDMENU_FORM_SAVE:'Save',
  	ADMIN_MENU_ADDMENU_FORM_CANCEL:'Cancel',
  	
})