i18n.map('en', {
  ADMIN_COMPONENTS_TAGS:'Tags',
  ADMIN_COMPONENTS_TAGS_ADDTAGS: ' Add Tag',
  ADMIN_COMPONENTS_TAGS_EDITTAG:'Edit Tag',
  ADMIN_COMPONENTS_TAGS_ADDTAGS_FORM_TAGNAME:'Tag name',
  ADMIN_COMPONENTS_TAGS_ADDTAGS_FORM_DESCRIPTION :'Description',

  ADMIN_COMPONENTS_TAGS_ADDTAGS_FORM_METAKEYWORD:'Meta Keyword',
  ADMIN_COMPONENTS_TAGS_ADDTAGS_FORM_METADESCRIPTION:'Meta Description',
  ADMIN_COMPONENTS_TAGS_ADDTAGS_FORM_SAVE:'Save',
  ADMIN_COMPONENTS_TAGS_ADDTAGS_FORM_CANCEL:'Cancel'
});