i18n.map('en',{
	ADMIN_SETTINGS_GLOBALCONFIGURATION:'Global Configuration',
	ADMIN_SETTINGS_NAME:'Name',
	ADMIN_SETTINGS_SITE_META_KEYWORD:'Meta Keyword',
	ADMIN_SETTINGS_SITE_META_DESCRIPTION:'Meta Description',
	ADMIN_SETTINGS_SITE_OFFLINE:'Site Offline',
	ADMIN_SETTINGS_SITE_OFFLINE_YES:'Yes',
	ADMIN_SETTINGS_SITE_OFFLINE_NO:'No',
	ADMIN_SETTINGS_CHANGE:'Update',
	ADMIN_SETTINGS_CANCEL:'Cancel'
});