i18n.map('en',{
	ADMIN_EXTENSION_MODULES:'',
  	ADMIN_EXTENSION_MODULES_ADDHTMLBLOCKS: 'Add HTML Blocks',
  	ADMIN_EXTENSION_MODULES_EDITHTMLBLOCKS:'Edit HTML Blocks',
  	ADMIN_EXTENSION_MODULES_ADDMODULE_FORM_TITLE:'Title',
  	ADMIN_EXTENSION_MODULES_ADDMODULE_FORM_HTML:'HTML',
  	ADMIN_EXTENSION_MODULES_ADDMODULE_FORM_POSITION:'Position',
  	ADMIN_EXTENSION_MODULES_ADDMODULE_FORM_MENU:'Menu',
  	ADMIN_EXTENSION_MODULES_ADDMODULE_FORM_STATUS:'Status',
  	ADMIN_EXTENSION_MODULES_ADDMODULE_FORM_TYPE:'Type',
  	ADMIN_EXTENSION_MODULES_ADDMODULE_FORM_ID:'ID',
  	ADMIN_EXTENSION_MODULES_ADDMODULE_FORM_SAVE:'Save',
  	ADMIN_EXTENSION_MODULES_ADDMODULE_FORM_CANCEL:'Cancel',
  	ADMIN_EXTENSION_MODULES_ADDMODULE_FORM_UPDATE:'Update',
  	ADMIN_EXTENSION_MODULES_ADDMODULE_FORM_REMOVE:'Remove'
})